"""model changes

Revision ID: 20b70c635f6c
Revises: 2d17dd89ca28
Create Date: 2024-02-16 11:00:51.441525

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '20b70c635f6c'
down_revision: Union[str, None] = '2d17dd89ca28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cell_ibfk_1', 'cell', type_='foreignkey')
    op.drop_column('cell', 'leader_id')
    op.drop_constraint('member_ibfk_2', 'member', type_='foreignkey')
    op.create_foreign_key(None, 'member', 'cell', ['cell_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.create_foreign_key('member_ibfk_2', 'member', 'cell', ['cell_id'], ['id'])
    op.add_column('cell', sa.Column('leader_id', mysql.VARCHAR(length=50), nullable=False))
    op.create_foreign_key('cell_ibfk_1', 'cell', 'member', ['leader_id'], ['id'])
    # ### end Alembic commands ###
