"""edit tables

Revision ID: 556f5f6a0f41
Revises: dac156270541
Create Date: 2024-02-16 13:54:44.665439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '556f5f6a0f41'
down_revision: Union[str, None] = 'dac156270541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members_departments',
    sa.Column('member_id', sa.String(length=50), nullable=True),
    sa.Column('department_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ondelete='CASCADE')
    )
    op.drop_index('cell_id', table_name='cell_constituency')
    op.create_foreign_key(None, 'cell_constituency', 'cell', ['cell_id'], ['id'])
    op.create_foreign_key(None, 'cell_constituency', 'constituency', ['constituency_id'], ['id'])
    op.create_foreign_key(None, 'cell_leaders', 'cell', ['cell_id'], ['id'])
    op.create_foreign_key(None, 'cell_leaders', 'member', ['leader_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cell_leaders', type_='foreignkey')
    op.drop_constraint(None, 'cell_leaders', type_='foreignkey')
    op.drop_constraint(None, 'cell_constituency', type_='foreignkey')
    op.drop_constraint(None, 'cell_constituency', type_='foreignkey')
    op.create_index('cell_id', 'cell_constituency', ['cell_id'], unique=True)
    op.drop_table('members_departments')
    # ### end Alembic commands ###
