"""relationship info

Revision ID: 5b00ac91a4ed
Revises: c38978949bf9
Create Date: 2024-02-12 19:08:11.287501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b00ac91a4ed'
down_revision: Union[str, None] = 'c38978949bf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('member', sa.String(length=50), nullable=False))
    op.add_column('attendance', sa.Column('attendance_type', sa.String(length=50), nullable=False))
    op.create_foreign_key(None, 'attendance', 'attendance_type', ['attendance_type'], ['id'])
    op.create_foreign_key(None, 'attendance', 'member', ['member'], ['id'])
    op.add_column('cell', sa.Column('leader_id', sa.String(length=50), nullable=False))
    op.add_column('cell', sa.Column('constituency_id', sa.String(length=50), nullable=False))
    op.create_foreign_key(None, 'cell', 'member', ['leader_id'], ['id'])
    op.create_foreign_key(None, 'cell', 'constituency', ['constituency_id'], ['id'])
    op.add_column('department', sa.Column('leader', sa.String(length=50), nullable=False))
    op.create_foreign_key(None, 'department', 'member', ['leader'], ['id'])
    op.add_column('member', sa.Column('cell_id', sa.String(length=50), nullable=True))
    op.add_column('member', sa.Column('department_id', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'member', 'department', ['department_id'], ['id'])
    op.create_foreign_key(None, 'member', 'cell', ['cell_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.drop_column('member', 'department_id')
    op.drop_column('member', 'cell_id')
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.drop_column('department', 'leader')
    op.drop_constraint(None, 'cell', type_='foreignkey')
    op.drop_constraint(None, 'cell', type_='foreignkey')
    op.drop_column('cell', 'constituency_id')
    op.drop_column('cell', 'leader_id')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_column('attendance', 'attendance_type')
    op.drop_column('attendance', 'member')
    # ### end Alembic commands ###
