"""relationship udpt

Revision ID: 686dd316bb21
Revises: 7ad768f81518
Create Date: 2024-02-16 08:36:15.308855

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '686dd316bb21'
down_revision: Union[str, None] = '7ad768f81518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
