"""indexing changed

Revision ID: 76c6470a73a1
Revises: 5b00ac91a4ed
Create Date: 2024-02-13 08:58:57.295827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76c6470a73a1'
down_revision: Union[str, None] = '5b00ac91a4ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_member_nationality', table_name='member')
    op.create_index(op.f('ix_member_first_name'), 'member', ['first_name'], unique=False)
    op.create_index(op.f('ix_member_last_name'), 'member', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_last_name'), table_name='member')
    op.drop_index(op.f('ix_member_first_name'), table_name='member')
    op.create_index('ix_member_nationality', 'member', ['nationality'], unique=False)
    # ### end Alembic commands ###
