"""edit models

Revision ID: 7ad768f81518
Revises: 8266b237188a
Create Date: 2024-02-16 07:46:29.520249

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '7ad768f81518'
down_revision: Union[str, None] = '8266b237188a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
