"""empty message

Revision ID: 8266b237188a
Revises: aa89e486af41
Create Date: 2024-02-16 07:44:51.870604

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '8266b237188a'
down_revision: Union[str, None] = 'aa89e486af41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
