"""empty message

Revision ID: aa89e486af41
Revises: 8e3896669d25
Create Date: 2024-02-14 14:48:52.884298

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aa89e486af41'
down_revision: Union[str, None] = '8e3896669d25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member', 'department_id',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member', 'department_id',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=False)
    # ### end Alembic commands ###
