"""edit tables2

Revision ID: eaf07bcb5c1b
Revises: 556f5f6a0f41
Create Date: 2024-02-16 14:46:49.736764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eaf07bcb5c1b'
down_revision: Union[str, None] = '556f5f6a0f41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members_departments', 'member_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('members_departments', 'department_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members_departments', 'department_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('members_departments', 'member_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
